stc_band_bundle:
    resource: "@StcAppBundle/Controller/BandController.php"
    type: annotation
    prefix: /band

stc_venue_bundle:
    resource: "@StcAppBundle/Controller/VenueController.php"
    type: annotation
    prefix: /venue

#stc_band_bundle_api:
#    resource: "@StcAppBundle/Controller/Api/Rest/BandController.php"
#    type: rest
#    prefix: api/rest/{version}/acme
#    requirements:
#        version: latest|v1
#    defaults:
#       version: latest